// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCml_k_uzWQzvlvn9LydeuSFRPonuKaDtc',
    appId: '1:569777707505:web:7d218e1c81fc3a2f298c50',
    messagingSenderId: '569777707505',
    projectId: 'email-auth-2fed9',
    authDomain: 'email-auth-2fed9.firebaseapp.com',
    storageBucket: 'email-auth-2fed9.firebasestorage.app',
    measurementId: 'G-BKE8V6V5GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn-XvYFTwKgbxkukELu-PCSJyMBPG1rEg',
    appId: '1:569777707505:android:50b12ec0f2d81447298c50',
    messagingSenderId: '569777707505',
    projectId: 'email-auth-2fed9',
    storageBucket: 'email-auth-2fed9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa53s4v7U8Ogywk_zfGZMgCrBHMb-jsLA',
    appId: '1:569777707505:ios:52638a86e2467af9298c50',
    messagingSenderId: '569777707505',
    projectId: 'email-auth-2fed9',
    storageBucket: 'email-auth-2fed9.firebasestorage.app',
    iosBundleId: 'com.example.twitterLoginExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa53s4v7U8Ogywk_zfGZMgCrBHMb-jsLA',
    appId: '1:569777707505:ios:cd08908d7f6522c4298c50',
    messagingSenderId: '569777707505',
    projectId: 'email-auth-2fed9',
    storageBucket: 'email-auth-2fed9.firebasestorage.app',
    iosBundleId: 'com.example.twitterLoginExample.RunnerTests',
  );
}
